version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel_net
    # depends_on:
      # - db

  # db:
  #   image: mysql:8.0
  #   container_name: laravel_db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: toor
  #     MYSQL_PASSWORD: 567890zx.
  #     MYSQL_ROOT_PASSWORD: 567890zx.
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - laravel_net
  #   volumes:
  #     - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  db_data:
